# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.5/namespace.json
apiVersion: v1
kind: Namespace
metadata:
  name: soc-platform
  labels:
    app.kubernetes.io/part-of: agentic-ai-soc
