-- Memory System Database Schema
-- SQLite database for structured incident storage
-- Author: Abhinav
-- Date: November 2025

-- Main incidents table
CREATE TABLE IF NOT EXISTS INCIDENTS (
 
  -- Identifiers
  INCIDENT_ID TEXT PRIMARY KEY,
  SESSION_ID TEXT NOT NULL,
  FLOW_ID TEXT NOT NULL,
 
  -- Temporal
  TIMESTAMP TEXT NOT NULL,
  DETECTED_AT TEXT NOT NULL,
 
  -- Network information
  SRC_IP TEXT NOT NULL,
  DST_IP TEXT NOT NULL,
  SRC_PORT INTEGER,
  DST_PORT INTEGER,
  PROTOCOL TEXT,
 
  -- Detection results
  ML_PREDICTION TEXT, -- "malicious" or "benign"
  ML_CONFIDENCE REAL, -- 0.0 to 1.0
  ENSEMBLE_AGREEMENT REAL, -- Model agreement score
  -- Context analysis
  CONTEXT_FLAGS TEXT, -- JSON array of flags
  CONTEXT_REASONS TEXT, -- JSON array of reasons
  SUSPICION_SCORE REAL, -- 0.0 to 1.0
  -- LLM analysis
  LLM_SEVERITY TEXT, -- low, medium, high, critical
  LLM_CONFIDENCE REAL, -- 0.0 to 1.0
  LLM_ANALYSIS TEXT, -- Full analysis text
  LLM_REASONING TEXT, -- Step-by-step reasoning
  RECOMMENDED_ACTIONS TEXT, -- JSON array of actions
  -- Response
  RESPONSE_PLAN TEXT, -- Generated response plan
  ACTION_TAKEN TEXT, -- What was actually done
  WAS_SUCCESSFUL INTEGER, -- 0/1 boolean
  -- Embeddings (for FAISS indexing)
  EMBEDDING_ID INTEGER, -- Index in FAISS
  -- Metadata
  NOTES TEXT,
  CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
);

-- IP reputation tracking
CREATE TABLE IF NOT EXISTS IP_REPUTATION (
  IP_ADDRESS TEXT PRIMARY KEY,
 
  -- Statistics
  INCIDENT_COUNT INTEGER DEFAULT 0,
  MALICIOUS_COUNT INTEGER DEFAULT 0,
  BENIGN_COUNT INTEGER DEFAULT 0,
  MEDIUM_SEVERITY_COUNT INTEGER DEFAULT 0, -- LLM-detected medium severity incidents
  HIGH_SEVERITY_COUNT INTEGER DEFAULT 0, -- LLM-detected high severity incidents
  CRITICAL_SEVERITY_COUNT INTEGER DEFAULT 0, -- LLM-detected critical severity incidents
  -- Temporal
  FIRST_SEEN TEXT NOT NULL,
  LAST_SEEN TEXT NOT NULL,
 
  -- Dual scoring system (demonstrates ML vs Hybrid approach)
  ML_THREAT_SCORE REAL DEFAULT 0.0, -- ML-only threat score (for research comparison)
  THREAT_SCORE REAL DEFAULT 0.0, -- Hybrid ML+LLM threat score
  -- Attack patterns
  ATTACK_TYPES TEXT, -- JSON array of attack types seen
  TARGETED_ASSETS TEXT, -- JSON array of commonly targeted IPs
  -- Metadata
  NOTES TEXT,
  UPDATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Attack pattern library
CREATE TABLE IF NOT EXISTS ATTACK_PATTERNS (
  PATTERN_ID TEXT PRIMARY KEY,
  PATTERN_NAME TEXT NOT NULL,
  PATTERN_TYPE TEXT NOT NULL, -- reconnaissance, lateral_movement, exfiltration, etc.
  -- Indicators
  INDICATORS TEXT NOT NULL, -- JSON object with pattern indicators
  -- Related incidents
  INCIDENT_IDS TEXT, -- JSON array of related incident IDs
  OCCURRENCE_COUNT INTEGER DEFAULT 0,
 
  -- Metadata
  FIRST_DETECTED TEXT NOT NULL,
  LAST_DETECTED TEXT NOT NULL,
  CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Correlation tracking (for multi-stage attacks)
CREATE TABLE IF NOT EXISTS INCIDENT_CORRELATIONS (
  CORRELATION_ID TEXT PRIMARY KEY,
 
  -- Related incidents
  INCIDENT_ID_1 TEXT NOT NULL,
  INCIDENT_ID_2 TEXT NOT NULL,
 
  -- Correlation details
  CORRELATION_TYPE TEXT NOT NULL, -- same_ip, same_target, temporal, pattern_based
  SIMILARITY_SCORE REAL, -- 0.0 to 1.0
  -- Temporal relationship
  TIME_DIFF_SECONDS INTEGER,
 
  -- Metadata
  CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (INCIDENT_ID_1) REFERENCES INCIDENTS(INCIDENT_ID),
  FOREIGN KEY (INCIDENT_ID_2) REFERENCES INCIDENTS(INCIDENT_ID)
);

-- System statistics (for quick metrics)
CREATE TABLE IF NOT EXISTS MEMORY_STATS (
  STAT_KEY TEXT PRIMARY KEY,
  STAT_VALUE TEXT NOT NULL,
  UPDATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS IDX_INCIDENTS_SRC_IP ON INCIDENTS(SRC_IP);

CREATE INDEX IF NOT EXISTS IDX_INCIDENTS_DST_IP ON INCIDENTS(DST_IP);

CREATE INDEX IF NOT EXISTS IDX_INCIDENTS_TIMESTAMP ON INCIDENTS(TIMESTAMP);

CREATE INDEX IF NOT EXISTS IDX_INCIDENTS_SEVERITY ON INCIDENTS(LLM_SEVERITY);

CREATE INDEX IF NOT EXISTS IDX_INCIDENTS_SESSION ON INCIDENTS(SESSION_ID);

CREATE INDEX IF NOT EXISTS IDX_IP_REPUTATION_THREAT_SCORE ON IP_REPUTATION(THREAT_SCORE DESC);

CREATE INDEX IF NOT EXISTS IDX_IP_REPUTATION_LAST_SEEN ON IP_REPUTATION(LAST_SEEN);

CREATE INDEX IF NOT EXISTS IDX_CORRELATIONS_INCIDENT1 ON INCIDENT_CORRELATIONS(INCIDENT_ID_1);

CREATE INDEX IF NOT EXISTS IDX_CORRELATIONS_INCIDENT2 ON INCIDENT_CORRELATIONS(INCIDENT_ID_2);

-- Views for common queries
CREATE VIEW IF NOT EXISTS RECENT_INCIDENTS AS
  SELECT
    INCIDENT_ID,
    TIMESTAMP,
    SRC_IP,
    DST_IP,
    LLM_SEVERITY,
    LLM_ANALYSIS
  FROM
    INCIDENTS
  ORDER BY
    TIMESTAMP DESC LIMIT 100;

CREATE VIEW IF NOT EXISTS HIGH_RISK_IPS AS
  SELECT
    IP_ADDRESS,
    INCIDENT_COUNT,
    MALICIOUS_COUNT,
    THREAT_SCORE,
    LAST_SEEN
  FROM
    IP_REPUTATION
  WHERE
    THREAT_SCORE > 0.7
  ORDER BY
    THREAT_SCORE DESC;